2020-05-25 18:32:45,250 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.3
2020-05-25 18:32:45,250 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\hans\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2020-05-25-18-32-45-mpf-Hans-PC.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2020-05-25 18:32:45,266 : INFO : Machine : MPF path: c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf
2020-05-25 18:32:45,266 : INFO : Machine : Machine path: C:\pinball\HauntedHouse
2020-05-25 18:32:45,266 : INFO : Machine : Platform: win32
2020-05-25 18:32:45,266 : INFO : Machine : Python executable location: c:\users\hans\appdata\local\programs\python\python36-32\python.exe
2020-05-25 18:32:45,266 : INFO : Machine : Python version: 3.6.8 (32-bit)
2020-05-25 18:32:45,266 : INFO : Machine : Machine config file #1: config.yaml
2020-05-25 18:32:45,266 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Hans\AppData\Local\Temp\6e040aaf1f6a41fde2348c429eac1a1c.mpf_cache
2020-05-25 18:32:45,281 : INFO : Machine : Initialise MPF.
2020-05-25 18:32:48,916 : INFO : ConfigValidator : Config spec file cache created: C:\Users\Hans\AppData\Local\Temp\config_spec.mpf_cache
2020-05-25 18:32:49,680 : INFO : P3-ROC : Connecting to P-ROC
2020-05-25 18:32:49,961 : INFO : P3-ROC : Successfully connected to P-ROC/P3-ROC. Firmware Version: 2. Firmware Revision: 6. Hardware Board ID: 1
2020-05-25 18:32:50,258 : INFO : EventManager : Event: ======'machine_var_p_roc_version'====== Args={'value': 2, 'prev_value': None, 'change': True}
2020-05-25 18:32:50,258 : INFO : EventManager : Event: ======'machine_var_p_roc_revision'====== Args={'value': 6, 'prev_value': None, 'change': True}
2020-05-25 18:32:50,258 : INFO : EventManager : Event: ======'machine_var_p_roc_hardware_version'====== Args={'value': 1, 'prev_value': None, 'change': True}
2020-05-25 18:32:50,304 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2020-05-25 18:32:50,616 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 29150, 'prev_value': None, 'change': True}
2020-05-25 18:32:50,616 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.3', 'prev_value': None, 'change': True}
2020-05-25 18:32:50,616 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.3, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2020-05-25 18:32:50,616 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.8', 'prev_value': None, 'change': True}
2020-05-25 18:32:50,616 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-7-6.1.7601-SP1', 'prev_value': None, 'change': True}
2020-05-25 18:32:50,616 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2020-05-25 18:32:50,616 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '7', 'prev_value': None, 'change': True}
2020-05-25 18:32:50,616 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '6.1.7601', 'prev_value': None, 'change': True}
2020-05-25 18:32:50,616 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86', 'prev_value': None, 'change': True}
2020-05-25 18:32:50,616 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2020-05-25 18:32:50,804 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Hans\AppData\Local\Temp\fd4d0ac963aaaec6abb4cac3da0cded0.mpf_cache
2020-05-25 18:32:50,819 : WARNING : ConfigProcessor : Config file in cache changed: C:\pinball\HauntedHouse\modes\attract\config\attract.yaml
2020-05-25 18:32:50,819 : INFO : ConfigProcessor : Loading config from file c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\modes\attract\config\attract.yaml.
2020-05-25 18:32:50,835 : INFO : ConfigProcessor : Loading config: c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\modes\attract\config\attract.yaml
2020-05-25 18:32:50,835 : INFO : ConfigProcessor : Loading config from file C:\pinball\HauntedHouse\modes\attract\config\attract.yaml.
2020-05-25 18:32:50,835 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 3\'',)>) at c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\events.py:99
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 3\'',)>) at c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\events.py:99>
Traceback (most recent call last):
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 193, in load
    config = self.process(f)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 218, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\constructor.py", line 111, in get_single_data
    return self.construct_document(node)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\constructor.py", line 121, in construct_document
    for _dummy in generator:
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\constructor.py", line 713, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "mode_attract_started" was defined multiple times in config   in "C:\\pinball\\HauntedHouse\\modes\\attract\\config\\attract.yaml", line 4, column 3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\events.py", line 102, in _async_handler_done
    future.result()
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\mode_controller.py", line 110, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\mode_controller.py", line 259, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\mode_controller.py", line 177, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 207, in load
    raise ValueError(msg)
ValueError: Error found in file C:\pinball\HauntedHouse\modes\attract\config\attract.yaml: 'Key "mode_attract_started" was defined multiple times in config   in "C:\\pinball\\HauntedHouse\\modes\\attract\\config\\attract.yaml", line 4, column 3'
2020-05-25 18:32:50,897 : INFO : Machine : Starting the main run loop.
2020-05-25 18:32:50,913 : INFO : Machine : Shutting down...
2020-05-25 18:32:50,913 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2020-05-25 18:32:50,928 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 193, in load
    config = self.process(f)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 218, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\constructor.py", line 111, in get_single_data
    return self.construct_document(node)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\constructor.py", line 121, in construct_document
    for _dummy in generator:
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\constructor.py", line 713, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "mode_attract_started" was defined multiple times in config   in "C:\\pinball\\HauntedHouse\\modes\\attract\\config\\attract.yaml", line 4, column 3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\machine.py", line 765, in _run_loop
    raise self._exception['exception']
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\events.py", line 102, in _async_handler_done
    future.result()
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\mode_controller.py", line 110, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\mode_controller.py", line 259, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\mode_controller.py", line 177, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 207, in load
    raise ValueError(msg)
ValueError: Error found in file C:\pinball\HauntedHouse\modes\attract\config\attract.yaml: 'Key "mode_attract_started" was defined multiple times in config   in "C:\\pinball\\HauntedHouse\\modes\\attract\\config\\attract.yaml", line 4, column 3'
2020-05-25 18:32:51,006 : INFO : root : MPF run loop ended.
