2020-05-20 17:32:31,591 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.3
2020-05-20 17:32:31,591 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\hans\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2020-05-20-17-32-31-mpf-Hans-PC.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2020-05-20 17:32:31,591 : INFO : Machine : MPF path: c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf
2020-05-20 17:32:31,591 : INFO : Machine : Machine path: C:\pinball\HauntedHouse
2020-05-20 17:32:31,591 : INFO : Machine : Platform: win32
2020-05-20 17:32:31,591 : INFO : Machine : Python executable location: c:\users\hans\appdata\local\programs\python\python36-32\python.exe
2020-05-20 17:32:31,591 : INFO : Machine : Python version: 3.6.8 (32-bit)
2020-05-20 17:32:31,591 : INFO : Machine : Machine config file #1: config.yaml
2020-05-20 17:32:31,607 : WARNING : ConfigProcessor : Config file in cache changed: C:\pinball\HauntedHouse\config\config.yaml
2020-05-20 17:32:31,607 : INFO : ConfigProcessor : Loading config from file c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\mpfconfig.yaml.
2020-05-20 17:32:32,496 : INFO : ConfigProcessor : Loading config: c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\mpfconfig.yaml
2020-05-20 17:32:37,644 : INFO : ConfigValidator : Config spec file cache created: C:\Users\Hans\AppData\Local\Temp\config_spec.mpf_cache
2020-05-20 17:32:37,753 : INFO : ConfigProcessor : Loading config from file C:\pinball\HauntedHouse\config\config.yaml.
2020-05-20 17:32:38,393 : ERROR : root : YAML error found in file C:\pinball\HauntedHouse\config\config.yaml. Line 270, Position 2: while parsing a block mapping
  in "C:\pinball\HauntedHouse\config\config.yaml", line 9, column 1
expected <block end>, but found '<block mapping start>'
  in "C:\pinball\HauntedHouse\config\config.yaml", line 270, column 2
Traceback (most recent call last):
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 193, in load
    config = self.process(f)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 218, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\composer.py", line 78, in get_single_node
    document = self.compose_document()
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\composer.py", line 101, in compose_document
    node = self.compose_node(None, None)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\composer.py", line 211, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\parser.py", line 141, in check_event
    self.current_event = self.state()
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\ruamel\yaml\parser.py", line 581, in parse_block_mapping_key
    token.start_mark,
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "C:\pinball\HauntedHouse\config\config.yaml", line 9, column 1
expected <block end>, but found '<block mapping start>'
  in "C:\pinball\HauntedHouse\config\config.yaml", line 270, column 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\commands\game.py", line 226, in __init__
    self.machine = MachineController(mpf_path, machine_path, vars(self.args))
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\machine.py", line 199, in __init__
    self._load_config()
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\machine.py", line 431, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\hans\appdata\local\programs\python\python36-32\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 200, in load
    raise ValueError(msg)
ValueError: YAML error found in file C:\pinball\HauntedHouse\config\config.yaml. Line 270, Position 2: while parsing a block mapping
  in "C:\pinball\HauntedHouse\config\config.yaml", line 9, column 1
expected <block end>, but found '<block mapping start>'
  in "C:\pinball\HauntedHouse\config\config.yaml", line 270, column 2
