2024-12-01 11:42:13,584 : INFO : root : Loading config.
2024-12-01 11:42:13,587 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-12-01 11:42:13,587 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/a187413b8cf7049e0b91852f54cd1afa.mpf_cache
2024-12-01 11:42:13,617 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/2e30198d1c841d95b9b3e69c8a0bb49b.mpf_cache
2024-12-01 11:42:13,617 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/40928215bbb65374348eff3d4cd7b8bc.mpf_cache
2024-12-01 11:42:13,617 : WARNING : ConfigProcessor : Config file in cache changed: /Users/C_Alan/pinball/hauntedhouse/modes/base/config/base.yaml
2024-12-01 11:42:13,617 : INFO : ConfigProcessor : Loading config from file /Users/C_Alan/pinball/hauntedhouse/modes/base/config/base.yaml.
2024-12-01 11:42:13,624 : INFO : ConfigProcessor : Loading config: /Users/C_Alan/pinball/hauntedhouse/modes/base/config/base.yaml
2024-12-01 11:42:13,625 : INFO : ConfigProcessor : Config file cache created: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/167ddff969183ffa73a4682c84ddf638.mpf_cache
2024-12-01 11:42:13,625 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/2e30198d1c841d95b9b3e69c8a0bb49b.mpf_cache
2024-12-01 11:42:13,625 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/f3e7df0542012602a298ddb9f31df321.mpf_cache
2024-12-01 11:42:13,626 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/ac27afd8b01174f1412801db135abc1d.mpf_cache
2024-12-01 11:42:13,626 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/df2857c909c4a913cc732702f1a197bb.mpf_cache
2024-12-01 11:42:13,626 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/1ab5c5e749213b44f20a4087626085fd.mpf_cache
2024-12-01 11:42:13,626 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/176bdc82e0948b16c38e3d140ac1de4b.mpf_cache
2024-12-01 11:42:13,627 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev5
2024-12-01 11:42:13,627 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-12-01-11-42-13-mpf-Macpro.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': '/Users/C_Alan/pinball/hauntedhouse/logs/2024-12-01-11-42-13-mpf-Macpro.local.log'}
2024-12-01 11:42:13,627 : INFO : Machine : MPF path: /Users/C_Alan/envp311/lib/python3.11/site-packages/mpf
2024-12-01 11:42:13,627 : INFO : Machine : Machine path: /Users/C_Alan/pinball/hauntedhouse
2024-12-01 11:42:13,627 : INFO : Machine : Platform: darwin
2024-12-01 11:42:13,627 : INFO : Machine : Python executable location: /Users/C_Alan/envp311/bin/python3.11
2024-12-01 11:42:13,627 : INFO : Machine : Python version: 3.11.0 (64-bit)
2024-12-01 11:42:13,627 : INFO : Machine : Initializing MPF...
2024-12-01 11:42:13,654 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-12-01 11:42:13,661 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-12-01 11:42:13,661 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 32800, 'prev_value': None, 'change': True}
2024-12-01 11:42:13,661 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev5', 'prev_value': None, 'change': True}
2024-12-01 11:42:13,661 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev5, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-12-01 11:42:13,661 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.11.0', 'prev_value': None, 'change': True}
2024-12-01 11:42:13,672 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-14.6.1-x86_64-i386-64bit', 'prev_value': None, 'change': True}
2024-12-01 11:42:13,672 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2024-12-01 11:42:13,672 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '23.6.0', 'prev_value': None, 'change': True}
2024-12-01 11:42:13,672 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64', 'prev_value': None, 'change': True}
2024-12-01 11:42:13,672 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2024-12-01 11:42:13,672 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': '/Users/C_Alan/pinball/hauntedhouse/logs/2024-12-01-11-42-13-mpf-Macpro.local.log', 'prev_value': None, 'change': True}
2024-12-01 11:42:13,673 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-12-01 11:42:13,709 : INFO : EventManager : Event: ======'drop_target_bank_upper_up'====== Args={}
2024-12-01 11:42:13,709 : INFO : EventManager : Event: ======'drop_target_bank_lower_up'====== Args={}
2024-12-01 11:42:13,711 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2024-12-01 11:42:13,715 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...color flash')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...color flash')>)>
Traceback (most recent call last):
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/light_player.py", line 122, in _convert_color
    color = RGBColor(color)
            ^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/rgb_color.py", line 177, in __init__
    self._color = RGBColor.string_to_rgb(color)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/rgb_color.py", line 420, in string_to_rgb
    raise ColorException("Invalid RGB string: {}".format(value))
mpf.core.rgb_color.ColorException: Invalid RGB string: flash

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/events.py", line 795, in _queue_task_done
    future.result()
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/device_config_player.py", line 56, in validate_config_entry
    raise e
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/device_config_player.py", line 83, in _validate_config_item
    raise e
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/device_config_player.py", line 80, in _validate_config_item
    device_settings = self._expand_device_config(device_settings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/light_player.py", line 133, in _expand_device_config
    device_settings['color'] = self._convert_color(color)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/light_player.py", line 124, in _convert_color
    self.raise_config_error("Invalid color {}".format(color), 1, source_exception=e, context=context)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Failed to load config player diverter_trapdoor_diverter_activating:lights with settings {'l_main_trap_door': 'flash'} >> Failed to expand entry "l_main_trap_door". >> Invalid color flash Error Code: CFE-light_player-1 (https://missionpinball.org/logs)
2024-12-01 11:42:13,719 : INFO : Machine : Starting the main run loop with active modes: []
2024-12-01 11:42:13,719 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2024-12-01 11:42:13,720 : INFO : Machine : Shutting down...
2024-12-01 11:42:13,720 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-12-01 11:42:14,722 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/light_player.py", line 122, in _convert_color
    color = RGBColor(color)
            ^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/rgb_color.py", line 177, in __init__
    self._color = RGBColor.string_to_rgb(color)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/rgb_color.py", line 420, in string_to_rgb
    raise ColorException("Invalid RGB string: {}".format(value))
mpf.core.rgb_color.ColorException: Invalid RGB string: flash

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/events.py", line 795, in _queue_task_done
    future.result()
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/device_config_player.py", line 56, in validate_config_entry
    raise e
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/device_config_player.py", line 83, in _validate_config_item
    raise e
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/device_config_player.py", line 80, in _validate_config_item
    device_settings = self._expand_device_config(device_settings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/light_player.py", line 133, in _expand_device_config
    device_settings['color'] = self._convert_color(color)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/config_players/light_player.py", line 124, in _convert_color
    self.raise_config_error("Invalid color {}".format(color), 1, source_exception=e, context=context)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Failed to load config player diverter_trapdoor_diverter_activating:lights with settings {'l_main_trap_door': 'flash'} >> Failed to expand entry "l_main_trap_door". >> Invalid color flash Error Code: CFE-light_player-1 (https://missionpinball.org/logs)
2024-12-01 11:42:14,724 : INFO : root : MPF run loop ended.
