2024-11-17 20:06:20,508 : INFO : root : Loading config.
2024-11-17 20:06:20,510 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-11-17 20:06:20,510 : WARNING : ConfigProcessor : Config file in cache changed: /home/caw/pinball/hauntedhouse/config/config.yaml
2024-11-17 20:06:20,510 : INFO : ConfigProcessor : Loading config from file /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/mpfconfig.yaml.
2024-11-17 20:06:20,517 : INFO : ConfigProcessor : Loading config: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/mpfconfig.yaml
2024-11-17 20:06:20,517 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/config/config.yaml.
2024-11-17 20:06:20,522 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/config/config.yaml
2024-11-17 20:06:20,523 : INFO : ConfigProcessor : Config file cache created: /tmp/248da7825a7099821037453685569d45.mpf_cache
2024-11-17 20:06:20,544 : INFO : ConfigProcessor : Loading config from cache: /tmp/95514865456cf95aac1ab02b2b9c91d4.mpf_cache
2024-11-17 20:06:20,545 : INFO : ConfigProcessor : Loading config from cache: /tmp/03ef85df1864fb5ef5b7e38cbf9eb8a8.mpf_cache
2024-11-17 20:06:20,545 : INFO : ConfigProcessor : Loading config from cache: /tmp/6dcc9600f5dbf9a99f5346cc5ca34ea9.mpf_cache
2024-11-17 20:06:20,546 : INFO : ConfigProcessor : Loading config from cache: /tmp/95514865456cf95aac1ab02b2b9c91d4.mpf_cache
2024-11-17 20:06:20,546 : INFO : ConfigProcessor : Loading config from cache: /tmp/2e5ac6493c6686883ff244e5da957f67.mpf_cache
2024-11-17 20:06:20,546 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev5
2024-11-17 20:06:20,546 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-11-17-20-06-20-mpf-caw-System-Product-Name.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'full_logfile_path': '/home/caw/pinball/hauntedhouse/logs/2024-11-17-20-06-20-mpf-caw-System-Product-Name.log'}
2024-11-17 20:06:20,546 : INFO : Machine : MPF path: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf
2024-11-17 20:06:20,546 : INFO : Machine : Machine path: /home/caw/pinball/hauntedhouse
2024-11-17 20:06:20,546 : INFO : Machine : Platform: linux
2024-11-17 20:06:20,546 : INFO : Machine : Python executable location: /home/caw/miniconda3/envs/envp311/bin/python
2024-11-17 20:06:20,546 : INFO : Machine : Python version: 3.11.10 (64-bit)
2024-11-17 20:06:20,547 : INFO : Machine : Initializing MPF...
2024-11-17 20:06:20,572 : INFO : P-Roc : Connecting to P-ROC
2024-11-17 20:06:20,578 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-17 20:06:20,578 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-17 20:06:21,584 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-17 20:06:21,584 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-17 20:06:22,590 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-17 20:06:22,590 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-17 20:06:23,597 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-17 20:06:23,597 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-17 20:06:24,203 : INFO : Machine : Starting the main run loop with active modes: []
2024-11-17 20:06:24,203 : ERROR : root : 'attract'
Traceback (most recent call last):
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/commands/game.py", line 229, in __init__
    self.machine.run()
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/core/machine.py", line 701, in run
    if not self.modes['attract'] in self.mode_controller.active_modes:
           ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'attract'
