2024-12-01 16:25:01,494 : INFO : root : Loading config.
2024-12-01 16:25:01,497 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-12-01 16:25:01,498 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/a187413b8cf7049e0b91852f54cd1afa.mpf_cache
2024-12-01 16:25:01,534 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/2e30198d1c841d95b9b3e69c8a0bb49b.mpf_cache
2024-12-01 16:25:01,535 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/40928215bbb65374348eff3d4cd7b8bc.mpf_cache
2024-12-01 16:25:01,535 : WARNING : ConfigProcessor : Config file in cache changed: /Users/C_Alan/pinball/hauntedhouse/modes/base/config/base.yaml
2024-12-01 16:25:01,535 : INFO : ConfigProcessor : Loading config from file /Users/C_Alan/pinball/hauntedhouse/modes/base/config/base.yaml.
2024-12-01 16:25:01,543 : INFO : ConfigProcessor : Loading config: /Users/C_Alan/pinball/hauntedhouse/modes/base/config/base.yaml
2024-12-01 16:25:01,544 : INFO : ConfigProcessor : Config file cache created: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/167ddff969183ffa73a4682c84ddf638.mpf_cache
2024-12-01 16:25:01,544 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/2e30198d1c841d95b9b3e69c8a0bb49b.mpf_cache
2024-12-01 16:25:01,544 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/f3e7df0542012602a298ddb9f31df321.mpf_cache
2024-12-01 16:25:01,544 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/ac27afd8b01174f1412801db135abc1d.mpf_cache
2024-12-01 16:25:01,545 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/df2857c909c4a913cc732702f1a197bb.mpf_cache
2024-12-01 16:25:01,545 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/1ab5c5e749213b44f20a4087626085fd.mpf_cache
2024-12-01 16:25:01,545 : INFO : ConfigProcessor : Loading config from cache: /var/folders/lw/36nc9wln17qdc1y8dnh6d85h0000gr/T/176bdc82e0948b16c38e3d140ac1de4b.mpf_cache
2024-12-01 16:25:01,545 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev5
2024-12-01 16:25:01,545 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-12-01-16-25-01-mpf-Macpro.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': '/Users/C_Alan/pinball/hauntedhouse/logs/2024-12-01-16-25-01-mpf-Macpro.local.log'}
2024-12-01 16:25:01,545 : INFO : Machine : MPF path: /Users/C_Alan/envp311/lib/python3.11/site-packages/mpf
2024-12-01 16:25:01,545 : INFO : Machine : Machine path: /Users/C_Alan/pinball/hauntedhouse
2024-12-01 16:25:01,545 : INFO : Machine : Platform: darwin
2024-12-01 16:25:01,545 : INFO : Machine : Python executable location: /Users/C_Alan/envp311/bin/python3.11
2024-12-01 16:25:01,545 : INFO : Machine : Python version: 3.11.0 (64-bit)
2024-12-01 16:25:01,546 : INFO : Machine : Initializing MPF...
2024-12-01 16:25:01,581 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-12-01 16:25:01,589 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-12-01 16:25:01,589 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 32800, 'prev_value': None, 'change': True}
2024-12-01 16:25:01,589 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev5', 'prev_value': None, 'change': True}
2024-12-01 16:25:01,589 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev5, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-12-01 16:25:01,589 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.11.0', 'prev_value': None, 'change': True}
2024-12-01 16:25:01,603 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-14.6.1-x86_64-i386-64bit', 'prev_value': None, 'change': True}
2024-12-01 16:25:01,603 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2024-12-01 16:25:01,603 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '23.6.0', 'prev_value': None, 'change': True}
2024-12-01 16:25:01,603 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64', 'prev_value': None, 'change': True}
2024-12-01 16:25:01,604 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2024-12-01 16:25:01,604 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': '/Users/C_Alan/pinball/hauntedhouse/logs/2024-12-01-16-25-01-mpf-Macpro.local.log', 'prev_value': None, 'change': True}
2024-12-01 16:25:01,604 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-12-01 16:25:01,637 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...not a dict.')>) at /Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/events.py:124
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...not a dict.')>) at /Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/events.py:124>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/events.py", line 127, in _async_handler_done
    future.result()
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/device_manager.py", line 89, in _load_device_modules
    await self.machine.mode_controller.load_mode_devices()
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/mode_controller.py", line 86, in load_mode_devices
    await mode.load_mode_devices()
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/mode.py", line 438, in load_mode_devices
    settings = device.validate_and_parse_config(settings, True, "mode:" + self.name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/devices/shot.py", line 79, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/config_validator.py", line 274, in validate_config_item
    return self._validate_dict(item_type, validation, validation_failure_info, item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/config_validator.py", line 290, in _validate_dict
    raise self.validation_error(item, validation_failure_info, "Item is not a dict.", 12)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry mode:base:shots:left_inlane:show_tokens = "l_main_trap_door" is not valid. Item is not a dict. Error Code: CFE-ConfigValidator-12 (https://missionpinball.org/logs)
2024-12-01 16:25:01,644 : INFO : Machine : Starting the main run loop with active modes: []
2024-12-01 16:25:01,644 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2024-12-01 16:25:01,644 : INFO : Machine : Shutting down...
2024-12-01 16:25:01,644 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-12-01 16:25:02,646 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/events.py", line 127, in _async_handler_done
    future.result()
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/device_manager.py", line 89, in _load_device_modules
    await self.machine.mode_controller.load_mode_devices()
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/mode_controller.py", line 86, in load_mode_devices
    await mode.load_mode_devices()
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/mode.py", line 438, in load_mode_devices
    settings = device.validate_and_parse_config(settings, True, "mode:" + self.name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/devices/shot.py", line 79, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/config_validator.py", line 274, in validate_config_item
    return self._validate_dict(item_type, validation, validation_failure_info, item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/C_Alan/envp311/lib/python3.11/site-packages/mpf/core/config_validator.py", line 290, in _validate_dict
    raise self.validation_error(item, validation_failure_info, "Item is not a dict.", 12)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry mode:base:shots:left_inlane:show_tokens = "l_main_trap_door" is not valid. Item is not a dict. Error Code: CFE-ConfigValidator-12 (https://missionpinball.org/logs)
2024-12-01 16:25:02,647 : INFO : root : MPF run loop ended.
